### PR TITLE
Update story.md

### PR DESCRIPTION
**Pull request by alesdonoso**
Add design section to Requirements in the story template.

### CODE REVIEW

**Comment by alesdonoso** [comment]
WDYT? I see the value by adding this, as many of our stories require a design work, and we don't have a specific section for this work to be shared.

**Comment by gorkalaucirica** [comment]
We can try. In case no design is required we can simply erase that block. I would add also a similar block for epics

**Review by gorkalaucirica — APPROVED** [review]

**Comment by alesdonoso** [comment]
> We can try. In case no design is required we can simply erase that block. I would add also a similar block for epics

i would do it too. We are normally adding "Part of ${EPIC}" text manually but i think it's valuable having a section specifically for that. Do you want me to add it as well?

**Comment by gorkalaucirica** [comment]
> Do you want me to add it as well?

Yes please

**Comment by gorkalaucirica** [comment]
Sorry, I misunderstood. What I meant was that epic.md should have a similar block. When you link a story from an epic, GitHub already adds "Tracked by" on top, therefore "Part of {epic}" is not necessary

Captura de pantalla 2023-04-03 a las 10 17 45

**Comment by alesdonoso** [comment]
oh, sorry. Yes, we can do that there as well. I've pushed back the last change, pls review again 🙏

**Review by gorkalaucirica — APPROVED** [review]

**Pull request merged**
